services:

    api:
        image: 'bookshop:latest'
        build:
            context: .
        environment:
            - 'POSTGRES_HOST=db'
        ports:
            - '8080:8080'
            - '8787:8787'
        networks:
            - bookshop_network

    db:
        image: 'postgres:latest'
        environment:
            - 'POSTGRES_DB=postgres'
            - 'POSTGRES_USER=postgres'
            - 'POSTGRES_PASSWORD=postgres'
        ports:
            - '5432:5432'
        volumes:
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - bookshop_network

networks:
    bookshop_network:
